title: Laravel Partitions via Migrations
theme: jekyll-theme-minimal
description: A Laravel that extends Illuminate to enable partitioned table creation within Laravel migrations.
show_downloads: true
